package com.flir.atlassdk.acecamerasample.export;

import com.flir.atlassdk.acecamerasample.storage.ScanRecord;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

public class ReportFormatter {
    
    /**
     * Format scan as human-readable text report
     */
    public static String formatTextReport(ScanRecord scan) {
        StringBuilder report = new StringBuilder();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US);
        
        report.append("═══════════════════════════════════\n");
        report.append("    AgriPulse Scan Report\n");
        report.append("═══════════════════════════════════\n\n");
        
        // Basic info
        report.append("Scan ID: ").append(scan.scanId).append("\n");
        report.append("Date: ").append(sdf.format(new Date(scan.timestamp))).append("\n");
        report.append("Animal ID: ").append(scan.animalId).append("\n");
        report.append("Species: ").append(scan.species).append("\n");
        
        // Add GPS location
        if (scan.latitude != 0.0 || scan.longitude != 0.0) {
            report.append("Location: ").append(
                com.flir.atlassdk.acecamerasample.location.LocationTracker.formatLocation(
                    scan.latitude, scan.longitude)).append("\n");
        }
        report.append("\n");
        
        // Health status
        report.append("───────────────────────────────────\n");
        report.append("HEALTH STATUS\n");
        report.append("───────────────────────────────────\n");
        report.append("Status: ").append(scan.overallStatus);
        report.append(" (").append(String.format("%.0f%%", scan.confidence * 100)).append(" confidence)\n");
        report.append("Reason: ").append(scan.statusReason).append("\n\n");
        
        // Body part temperatures
        report.append("───────────────────────────────────\n");
        report.append("BODY PART TEMPERATURES\n");
        report.append("───────────────────────────────────\n");
        
        for (ScanRecord.BodyPartData part : scan.bodyParts.values()) {
            report.append(String.format("%-20s", formatBodyPartName(part.name)));
            report.append(String.format("T95: %.1fK (%.1f°C)", part.t95, kelvinToCelsius(part.t95)));
            
            // Add warning indicator for suspected areas
            if ("SUSPECTED".equals(scan.overallStatus) && 
                scan.statusReason.toLowerCase().contains(part.name.toLowerCase())) {
                report.append(" [!]");  // ASCII warning
            }
            report.append("\n");
            
            report.append(String.format("%-20s", ""));
            report.append(String.format("Mean: %.1fK, Std: %.2fK", part.mean, part.std));
            report.append("\n\n");
        }
        
        // Recommendation
        report.append("───────────────────────────────────\n");
        report.append("RECOMMENDATION\n");
        report.append("───────────────────────────────────\n");
        
        if ("SUSPECTED".equals(scan.overallStatus)) {
            report.append("[!] VETERINARY EXAMINATION RECOMMENDED\n\n");
            report.append("This animal shows signs of elevated\n");
            report.append("temperature that may indicate illness.\n");
            report.append("Please schedule a veterinary checkup.\n\n");
        } else {
            report.append("[OK] No immediate concerns detected\n\n");
            report.append("Continue regular monitoring.\n\n");
        }
        
        // Footer
        report.append("───────────────────────────────────\n");
        report.append("Generated by AgriPulse v1.0\n");
        report.append("Thermal Livestock Wellness Monitor\n");
        report.append("───────────────────────────────────\n\n");
        
        report.append("DISCLAIMER: This is a screening tool.\n");
        report.append("Always consult a veterinarian for\n");
        report.append("medical diagnosis and treatment.\n");
        
        return report.toString();
    }
    
    /**
     * Format scan as CSV
     */
    public static String formatCSV(ScanRecord scan) {
        StringBuilder csv = new StringBuilder();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US);
        
        // Header
        csv.append("scan_id,timestamp,animal_id,species,body_part,t95_kelvin,mean_kelvin,std_kelvin,");
        csv.append("t95_celsius,mean_celsius,overall_status,confidence,reason\n");
        
        // Data rows
        for (ScanRecord.BodyPartData part : scan.bodyParts.values()) {
            csv.append(scan.scanId).append(",");
            csv.append(sdf.format(new Date(scan.timestamp))).append(",");
            csv.append(scan.animalId).append(",");
            csv.append(scan.species).append(",");
            csv.append(part.name).append(",");
            csv.append(String.format("%.2f", part.t95)).append(",");
            csv.append(String.format("%.2f", part.mean)).append(",");
            csv.append(String.format("%.2f", part.std)).append(",");
            csv.append(String.format("%.2f", kelvinToCelsius(part.t95))).append(",");
            csv.append(String.format("%.2f", kelvinToCelsius(part.mean))).append(",");
            csv.append(scan.overallStatus).append(",");
            csv.append(String.format("%.2f", scan.confidence)).append(",");
            csv.append("\"").append(scan.statusReason).append("\"");
            csv.append("\n");
        }
        
        return csv.toString();
    }
    
    /**
     * Format body part name for display
     */
    private static String formatBodyPartName(String name) {
        return name.replace("_", " ").toUpperCase();
    }
    
    /**
     * Convert Kelvin to Celsius
     */
    private static double kelvinToCelsius(double kelvin) {
        return kelvin - 273.15;
    }
}
